version: 2.1

jobs:
  config_environnement:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout 
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project-ml-microservice-kubernetes/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv devops
            . devops/bin/activate 
            cd project-ml-microservice-kubernetes 
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                chmod +x /bin/hadolint
      - save_cache:
          paths:
            - devops
          key: v1-dependencies-{{ checksum "project-ml-microservice-kubernetes/requirements.txt" }}

  # run lint!
  run_lint:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project-ml-microservice-kubernetes/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: run lint
          command: |
            # python3 -m venv devops
            # . devops/bin/activate 
            cd project-ml-microservice-kubernetes
            make lint 

  # - run:
  #   # installs a docker client that will be used to run the docker commands
  #     name: Install Docker client
  #     command: |
  #       set -x
  #       VER="20.10.11"
  #       curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
  #       tar -xz -C /tmp -f /tmp/docker-$VER.tgz
  #       mv /tmp/docker/* /usr/bin

  # # build docker image and run container!
  # - run:
  #     name: build docker image and run container
  #     command: | 
  #       cd project-ml-microservice-kubernetes
  #       chmod +x ./run_docker.sh
  #       ./run_docker.sh  

  # # write docker logs to output_txt_files/docker_out.txt
  # - run:
  #     name: write docker logs to output_txt_files/docker_out.txt
  #     command: | 
  #       cd project-ml-microservice-kubernetes
  #       docker logs -f ml_app &> output_txt_files/docker_out.txt & 



workflows:
  default:
    jobs:
      - config_environnement
      # 
      - run_lint:
          requires:
            - config_environnement